### ISSUE TITLE
Parsing Dynamic Webpage

### ISSUE THREAD

**Issue by Omi231** [tusharojha/web_scraper#1]
hi,

How to measure loading time. I want to check performance in miliseconds that how much time it takes to load a webpage. Can you please suggest me how can I do that?

**Comment by tusharojha** [comment]
Hello @Omi231, 

At present, web_scraper is not measuring loading time/performance but I am working on it and will provide that in the next update.

Thanks for reporting!

**Comment by Omi231** [comment]
@tusharojha I have one more question. Is it possible to access webpage <Script> tags which are inside head and body? There is a string variable inside a script tag, i want to access that.  

If its not possible using this plugin then how else can I achieve this?

Thanks for this plugin by the way. It is very convenient to use.

**Comment by tusharojha** [comment]
I feel glad to tell you that now you can fetch elapsed time as well.
Have a look to `develop` branch for recent updates. 

Package will be updated in the next version.

Thanks for reporting issues/improvements.

**Comment by tusharojha** [comment]
@Omi231 Thanks for your improvement suggestions!

Version 0.0.5 contains all the features you need.

For detailed info on scraping script variables using web_scraper 0.0.5, have a look on tests present in [web_scraper_test.dart](https://github.com/tusharojha/web_scraper/blob/master/test/web_scraper_test.dart)

**Comment by Omi231** [comment]
Thank you so much @tusharojha. I can't explain in words how much thankful i am. Stay blessed :)
