### ISSUE TITLE
how to extract the when there is a <br />?

### ISSUE THREAD

**Issue by iamshaunwu** [tusharojha/web_scraper#12]
Hi! My code is as follows.
`final titleElements = webScraper.getElement(
          'section.content__block.content__full > div.container > table.tr-table > tbody > tr > td',
          []);`

All is data scraped is good except when it comes to the below line.
`<td>SHOP NAME<br />Address</td>`

It will appear as SHOP NAMEAddress. Can you shed some light on how I can split into 2 elements? Thanks!

**Comment by iamshaunwu** [comment]
I found the solution.

**Comment by jordan-hamilton** [comment]
Any insight on how you accomplished this @iamshaunwu? I was hoping to replace br tags with newlines inside of a p tag, but I can see they were stripped in the output with a line like the following:
`final elements =
        webScraper.getElement('div.about > div > p', []);`

**Comment by iamshaunwu** [comment]
@jordan-hamilton it's complicated... hahaha... I replied to your .me email.

**Comment by tusharojha** [comment]
@iamshaunwu I think we should add this in the next version!

It would be a great help if you can describe your solution here as well.

And we can reopen this issue too.

**Comment by iamshaunwu** [comment]
@tusharojha 
Do pardon me. I feel a little embarrassed because I think my method is a little traditional. Moreover, I am 39 and I only started development since August 2020. Anyway, based on my needs, what i did was:
1. Use `webScraper.getPageContent()` to extract the html code from the webpage into a string variable.
2. Use .replaceAll to replace `<br />` with a tag that can be detected during the scraping process. In my case, I replaced <br /> with `</td><td>`.  That is to say, from `<td>SHOP Name**<br />**Address</td>` to `<td>SHOP Name**</td><td>**Address</td>`.
3. I copy the code for `webScraper.getElements()` into a separate class and made a mini amendment - Instead of parsing response.body to scrape, I parse a string to scrape. In this case the string will be the String variable that contains the new html code that already has <br /> replaced.

**Comment by tusharojha** [comment]
Thanks, @iamshaunwu for your response and filing this issue.
I appreciate your solution and will work on it to make a more generic, reusable & scalable to implement.

**Comment by tusharojha** [comment]
As this is a need-based thing so I think we cannot assume to add this feature for everyone. But the issue now can be fixed with the new function added to the library i.e. [loadFromString](https://github.com/tusharojha/web_scraper/blob/develop/lib/web_scraper.dart#L91). 

So, the whole process would be
- to remove `<br />` tags or replace with something else, first get the page source in a string using `getPageContent()`
- use `replaceAll()` function to replace string segments
- pass the new string to newly added `loadFromString` function

Sample code: 
```dart
webScraper.loadFromString(webScraper.getPageContent().replaceAll('<br />', '<td></td>'));
```
