### ISSUE TITLE
getScriptVariables RegEx issue

### ISSUE THREAD

**Issue by Hecsall** [tusharojha/web_scraper#13]
Hi, while using this package i noticed a bug on the regex used on the **getScriptVariables** function.
I'm trying to get a variable that contains a (huge) **JSON object**, but the problem is that inside one of the keys there is a semicolon (**;**) and this breaks the object because the regex thinks it's the end of the javascript variable.

I'm no regex expert to be honest, so i don't really know how this could be fixed, i just changed it from `.*?;` to `.*?(};|];)` but obviously it works only for my specific case where the variable ends with `};` or with `];`.

Here is an example of a variable containing a JSON object that breaks when parsed with the web scraper package:
```javascript
var someVar = {
	results: [
		{ "keyA": "valueA" },
		{ "keyB": "value;B" },
		{ "keyC": "valueC" }
	]
};
```
Link to regex101 example: https://regex101.com/r/Rlk2C6/1

Ideally i think the regex should ignore semicolons if they are between quotes so it should avoid them when contained inside values.

Hope it helps!

**Comment by tusharojha** [comment]
Hi @Hecsall!
Thanks for filing this issue.
You are right this is an issue that should be fixed on top priority. Maybe while writing the first suite, I was not thinking about it but surely now I will upgrade the primitive regex to something which satisfies the case of quote enclosure. 

It would be fixed in the next coming update.

Once again, Thanks for filing this issue. 👍

**Comment by tusharojha** [comment]
The issue will be closed after the patch gets merged to master.

**Comment by Hecsall** [comment]
Nice job, tested the new regex locally and it works like a charm, thanks!

**Comment by tusharojha** [comment]
The issue has been fixed in the latest version of the web_scraper.
Thanks for your contribution!
