### ISSUE TITLE
getElementTitle() and getElementAttribute()

### ISSUE THREAD

**Issue by TheYuriG** [tusharojha/web_scraper#21]
Hello, very useful package.

Trying to do a pull request with 2 new methods that return simplified Lists over a List of Maps.
Never used github before so figuring it out for now. Please do test if it works as expected before merging.

I've commented on all 3 to make easier for new users to the package, as I had no previous experience with non-cheerio web scraping so i'm hoping my notes will help others to have an easier time than I had when i first started.

**Comment by TheYuriG** [comment]
Could not figure out how to branch and do a pull request, but here is the code:
https://paste.ofcode.org/YhJvUkpZqS3c7HJVBek8h3

**Comment by tusharojha** [comment]
Hi @TheYuriG,

I am happy to see your interest in contributing to this package and you're welcome as well. Honestly, I have been thinking to simplify the current data structures for the package, making it simpler & scalable for developers to use.  It can be a good alternative as of now and keeping it as a separate option without directly changing the current pattern.

> Could not figure out how to branch and do a pull request

Check out this video tutorial in which I have explained everything about contributing to opensource: https://www.youtube.com/watch?v=oHPUZ1qupNY

**Comment by TheYuriG** [comment]
> Hi @TheYuriG,
> 
> I am happy to see your interest in contributing to this package and you're welcome as well. 
Thank you! Happy to give some back after taking so much!

> Honestly, I have been thinking to simplify the current data structures for the package, making it simpler & scalable for developers to use. It can be a good alternative as of now and keeping it as a separate option without directly changing the current pattern.
Yeah, my idea was not to do any breaking changes so everyone could use this update without having any breaking changes.

> Check out this video tutorial in which I have explained everything about contributing to opensource: https://www.youtube.com/watch?v=oHPUZ1qupNY
Will take a look. I had to bail for the day last time i posted so i just didn't want to be one of _those guys_ that promise something and then just disappear for days. Will try doing the proper way next time.
