### ISSUE TITLE
Cant get data from Ajax page

### ISSUE THREAD

**Issue by izark99** [tusharojha/web_scraper#24]
Link: https://fimnhe.net/xem-phim/hanh-phuc-nho-cua-anh-my-little-happiness-tap-1-server-1

My code: 
![image](https://user-images.githubusercontent.com/20470671/105958956-e0ad6200-60ad-11eb-82a8-78105f712b13.png)

_tempList is empty.
I want to get src like this.
![image](https://user-images.githubusercontent.com/20470671/105959087-0aff1f80-60ae-11eb-9c7d-a8a6bbd5525b.png)

I'm newbie so sorry if this question is annoy.

**Comment by tusharojha** [comment]
Thanks for filling the issue @izark99. This is something unexpected, I have to take a look into this. 

Although, I think this can because of some script blocking the web_scraper to get the elements.

I will provide updates regarding this after testing some more cases.

**Comment by izark99** [comment]
Have any solutions for this? I try but still cant. 
Hope to have your reply.

**Comment by TheYuriG** [comment]
This is rendered through javascript. If you load the page with javascript disabled, that `div#ajax-player` stays forever empty.
I don't believe you can get the content of that div through the method you are currently deploying.
Think the only solutions are to either mimick the network requests the JS function is doing or use a framework that runs a browser window on background, like Puppeteer.

**Comment by tusharojha** [comment]
Sorry @izark99 for the late response, actually I was busy with my exams.
Thanks to @TheYuriG for adding info related to it. 

Feel free to open new issues for improving the package.
