### ISSUE TITLE
Getting attributes from elements that are not present consistently throughout the webpage

### ISSUE THREAD

**Issue by cyclothunder** [tusharojha/web_scraper#26]
In the following example I want to catch all text in element "td", but if exits an element "a", I will also want its "href" attribute.
Hope this makes sense to you.

<img width="328" alt="example" src="https://user-images.githubusercontent.com/2094896/107153672-b473ca00-6966-11eb-86bc-8eb49f7913c3.png">

I think there is no way to do this. Am I correct?

**Comment by cyclothunder** [comment]
I already have a proposed fix if you're interested.

**Comment by tusharojha** [comment]
Hi @cyclothunder!
Sorry for the late reply. Actually, I was in-active in the last couple of weeks. 
Also, I would love to know your fix and appreciate your contribution to improving the package.

**Comment by cyclothunder** [comment]
No problem.
Should I do a pull request? Or just paste it in a comment?

This will be my first contribution to an open source project :)

**Comment by tusharojha** [comment]
Make a pull request to add the feature & make sure to target develop branch. This would be a great start to open source ✨

**Comment by tusharojha** [comment]
Thanks for your contribution @cyclothunder!
