### ISSUE TITLE
Get Element Content

### ISSUE THREAD

**Issue by jleangstartup** [tusharojha/web_scraper#3]
Hi there. This is pretty nifty. I had a play around with your example.

Any chance you could grab content as well? (the same way you get Element attributes)

Like for example in your test website, if I wanted to grab the descriptions 

`<p class="description">Prestigio SmartBook 133S Dark Grey, 13.3&quot; FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>`

**Comment by tusharojha** [comment]
Hello @jleangstartup 
Unless I am misunderstanding, you want to get the data enclosed between the opening and closing tag. If yes, then its already available in the response of the getElement method.

In response, you will get the list of all occurrences of the prescribed address in arguments of method getElement. You can access the content by the fetching title from the returned object.

Here is an example:
If the following is a response from the getElement method.
```dart
[
    {
      "title": "Prestigio SmartBook 133S Dark Grey, 13.3&quot; FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1",
      "attributes": {
        "class: "description"
      }
    },
...
  ]
```

The content lies in the title property of the map. So, you can access it as follows:

```dart
String content = productDescription[index]["title']
```
I hope this will help!

**Comment by jleangstartup** [comment]
ah right my apologies. Yes that works.

I am having a bit of trouble accessing the description in your example page though.
Is this how I am meant to be doing it? It looks like it is expecting some attribs, but what if the <p> </p> does not have any attribs?

`        productNames = webScraper.getElement(
            //'div.thumbnail > div.caption > h4 > a.title', ['href', 'title']);
            'div.thumbnail > div.caption > p.description');`

**Comment by tusharojha** [comment]
As of now, it is required to pass the array of attributes you want to extract!
One possible way could be to pass the attribute by which you are finding the element.

Example:
```dart
productDescriptions = webScraper.getElement('div.thumbnail > div.caption > p.description', ['class'])
```
Since, you are fetching the element by its class i.e. description you can pass class in the array to make it work.

It would be fixed in the next version.

Thanks for reporting.

**Comment by jleangstartup** [comment]
ahh yup I added a

```
if attribs is not null { 
xxx
}
```

**Comment by tusharojha** [comment]
You can also make a pull request to the `develop` branch for it!

Thanks
I'm closing this issue now!
