### ISSUE TITLE
It seems that the copyright notice was not written correctly.

### ISSUE THREAD

**Issue by OzRagwort** [tusharojha/web_scraper#33]
I found it during an license and copyright notice.

It is currently written in the LICENSE file as follows.
Copyright [yyyy] [name of copyright owner]

I think it needs to be fixed.
For example "Copyright © 2020 tusharojha"

I'm sorry if I made a mistake because I didn't know.

**Comment by tusharojha** [comment]
Nice catch 👍 
I think I was very excited while deploying the first version of the package 😄

**Comment by tusharojha** [comment]
Fixed via #48.
Thanks for filing.
