### ISSUE TITLE
Can't scrap results from Ecosia anymore

### ISSUE THREAD

**Issue by ArnaudAngelo** [tusharojha/web_scraper#35]
Hi,

First of all, thanks for your package, it helps a lot !

Few months ago I succed to get the results of a research from www.ecosia.org but it suddenly stop working... I was able to display in a ListView, the title, the description and launch the related link of the website.

Here is my code :

```
//initialize WebScraper by passing base url of website
  final webScraper = WebScraper('https://www.ecosia.com');

  // Response of getElement is always List<Map<String, dynamic>>
  List<Map<String, dynamic>> siteNames;
  List<Map<String, dynamic>> siteDescriptions;

  void fetchProducts() async {
    // Loads web page and downloads into local state of library
    if (await webScraper.loadWebPage('/search?q=my+research')) {
      setState(() {
        // getElement takes the address of html tag/element and attributes you want to scrap from website
        // it will return the attributes in the same order passed
        siteNames = webScraper.getElement('div.result-firstline-container > h2 > a', ['href']);
        siteDescriptions = webScraper.getElement(
            'div.result-body > a.result-snippet-link > p.result-snippet',
            ['class']);
      });
      print(siteNames);
      print(siteDescriptions);
    }
  }
```

but the lists are empty.

So I tried to start over by simply getting the element `webScraper.getElement('div', ['class'])` and here is a part of the result :
```{title:
    <h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>
    Checking your browser before accessing ecosia.org.
      Please enable Cookies and reload the page.
    This process is automatic. Your browser will redirect to your requested content shortly.
    Please allow up to 5 seconds…
    Redirecting…
```

Thank you for your help !

**Comment by tusharojha** [comment]
Hi @ArnaudAngelo, Thanks for your interest in the package. 

It looks like the page is using `javascript` to redirect. websites generally use these in cases to protect from web scraping or maybe they are actually redirecting to a new URL.

So, I would suggest taking a deep dive inside the network tab of chrome dev tools.

**Comment by ArnaudAngelo** [comment]
Thank you @tusharojha for your answer.
So, do you think I can bypass this redirect or I should better use an other web browser?

**Comment by tusharojha** [comment]
Yes, you can try out by changing the web browser as well.
