### ISSUE TITLE
Cannot catch error in webScraper.loadWebPage('') !

### ISSUE THREAD

**Issue by anass-naoushi** [tusharojha/web_scraper#36]
If the user does not have an internet connection or fetching fails, the page keeps awaiting endlessly without returning an error. I tried adding try{} catch (e){throw 'error'} but did not work. This  must be fixed please. Thank you.

**Comment by tusharojha** [comment]
Hi @anass-naoushi!
Thanks for filing the issue. But I am not able to reproduce it. So, It would be great if you can give more info like the version you are using, network speed, etc.

I tried with the latest version while setting my machine to flight mode and it does showed be WebScraperException errors.

**Comment by tusharojha** [comment]
Closing this issue because of no response. Feel free to reopen if the issue persists.
