### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by Joseph-Nathan** [tusharojha/web_scraper#42]
j want to get google forms html url as List<Map> in dart
exp.
[exam url](https://docs.google.com/forms/d/e/1FAIpQLScZSDzsjcGQGDAMGRY1UBLCBMYOuaX7iPFrCxFZNSHTaZPsag/viewform?usp=sf_link)

can you help me by your package .

**Comment by tusharojha** [comment]
I need more explanation on this to help.

Some pointers would be:

- What are you doing? I mean which url you are scraping?
- What element you want to be scraped?
- What's your desired result?

**Comment by Joseph-Nathan** [comment]
sorry i fixed url ,
i work with exam app and need to get option to import question tom my exam from google form exam ,
element i want to scraping choose question form prev. url ,
desired result :
List<ChooseQuestion> question ,

sorry , i'm ban in web , thank for your time .

**Comment by Joseph-Nathan** [comment]
@tusharojha hi bro ,
are you reach for any idea !?

**Comment by tusharojha** [comment]
Hi @Joseph-Nathan!
Actually you can do this by trying different selectors. For example:

```dart
if (await webScraper.loadFullURL(
      'https://docs.google.com/forms/d/e/1FAIpQLScZSDzsjcGQGDAMGRY1UBLCBMYOuaX7iPFrCxFZNSHTaZPsag/viewform')) {
    try {
      var elements = webScraper
          .getElementTitle('div.freebirdFormviewerViewItemList > div');
      elements.sublist(2).forEach((img) => print(img)); // Taken sublist so that I can avoid Name field
    } catch (e) {
      print(e);
    }
  }
```

**Comment by Joseph-Nathan** [comment]
thanks bro it work fine ,
is that possible to split values because it's overlap ,
like "xxxxxxxxxxxxxxx%%xxxxxx%%xxxxxxxx"
%%  some thing to split between values .

thanks again .

**Comment by tusharojha** [comment]
You can try something like:

```dart

var str = "xxxxxxxxxxxxxxx%%xxxxxx%%xxxxxxxx";
var splittedArray =  str.split("%%");
for(var split in splittedArray){
  print(split);
}

```

**Comment by tusharojha** [comment]
Closing this issue as your questions are answered now.
Feel free to reopen if you still face the same problem.
