### ISSUE TITLE
Site Scraping that is locked behind login

### ISSUE THREAD

**Issue by venky9885** [tusharojha/web_scraper#43]
I want to perform site scraping that is present after logging

**Comment by tusharojha** [comment]
As of now, its not possible with `web_scraper` package, try puppeteer.

**Comment by venky9885** [comment]
I have seen puppeter, it seems doesn't support Android, can you suggest any other??

**Comment by tusharojha** [comment]
Then, I think should prefer doing the scraping task on a server. Though, I will let you know if I find any good mobile alternative.

**Comment by venky9885** [comment]
ok thanks
