### ISSUE TITLE
No option to set custom User-Agent

### ISSUE THREAD

**Issue by elRubenof** [tusharojha/web_scraper#53]
Hi, I´m scraping a web that some days has cloudflare enable and other ones no (i don´t know why), but when it is enable flutter can´t get the data from the web. There is any solution?

![Captura de pantalla 2021-07-06 a las 19 12 44](https://user-images.githubusercontent.com/52919665/124640798-33295080-de8e-11eb-98f0-dcbb9d64c9d6.png)

**Comment by tusharojha** [comment]
Not sure but I guess changing the User-Agent in header for get request would pass the cloud flare filter.

**Comment by elRubenof** [comment]
Sorry for the late, could you say me how to implement that on my code @tusharojha ??

Here is an example:

import 'package:web_scraper/web_scraper.dart';

var webScraper1 = WebScraper('https://example.com');
Future<void> test() async {
  if (await webScraper1.loadWebPage('/')) {
    var item = webScraper1.getElement('h1', ['title']);
  }
}

**Comment by tusharojha** [comment]
As of now, the web_scraper library is doesn't support to set custom User-Agent but would be fixed in the coming update.

**Comment by tusharojha** [comment]
Resolved in #61. Thanks to @koyachi.
